import type { GrammarLesson, GrammarSkillDef } from "./types";

/**
 * Why these five tenses? They cover ~90 % of everyday spoken English:
 * Present Simple (habits, facts), Present Continuous (right now / plans), Past Simple (stories,
 * "what did you do?"), Present Perfect (experience & recent results — the tense French speakers
 * confuse most with the passé composé) and Future forms (will / going to / present continuous
 * for plans). Other tenses (past continuous, conditionals…) come next as the learner progresses.
 */
export const GRAMMAR_SKILLS: GrammarSkillDef[] = [
  { slug: "present-simple", name: "Present simple", description: "Habitudes, faits, 3ᵉ personne en -s", level: "A1", lessonSlug: "present-simple" },
  { slug: "present-continuous", name: "Present continuous", description: "Actions en cours et projets proches", level: "A1", lessonSlug: "present-continuous" },
  { slug: "past-simple", name: "Past simple", description: "Actions terminées dans le passé, verbes irréguliers", level: "A2", lessonSlug: "past-simple" },
  { slug: "present-perfect", name: "Present perfect", description: "Expérience, résultat présent, for/since", level: "B1", lessonSlug: "present-perfect" },
  { slug: "future-forms", name: "Future forms", description: "will, going to, present continuous futur", level: "A2", lessonSlug: "future-forms" },
  { slug: "articles", name: "Articles", description: "a / an / the / pas d'article", level: "A1" },
  { slug: "prepositions", name: "Prepositions", description: "in / on / at, to / for, prépositions dépendantes", level: "A2" },
  { slug: "plurals", name: "Plurals & countable nouns", description: "Pluriels irréguliers, dénombrables / indénombrables", level: "A1" },
  { slug: "word-order", name: "Word order", description: "Ordre des mots, adverbes, questions", level: "A2" },
  { slug: "modal-verbs", name: "Modal verbs", description: "can, must, should, might…", level: "A2" },
  { slug: "comparatives", name: "Comparatives & superlatives", description: "taller than, the most…", level: "A2" },
  { slug: "conditionals", name: "Conditionals", description: "if + présent / prétérit", level: "B1" },
  { slug: "vocabulary-choice", name: "Word choice", description: "Mot juste, faux amis, collocations", level: "A2" },
  { slug: "spelling", name: "Spelling", description: "Orthographe", level: "A1" },
  { slug: "pronunciation", name: "Pronunciation", description: "Prononciation et accentuation", level: "A1" },
];

export const GRAMMAR_LESSONS: GrammarLesson[] = [
  {
    slug: "present-simple",
    skillSlug: "present-simple",
    title: "Present Simple",
    titleFr: "Le présent simple",
    level: "A1",
    summary:
      "Le présent simple décrit ce qui est vrai en général : habitudes, routines, faits, goûts. C'est le temps le plus utilisé pour se présenter et parler de sa vie.",
    whenToUse: [
      { text: "Habitudes et routines", example: "I get up at seven every day.", translation: "Je me lève à sept heures tous les jours." },
      { text: "Faits et vérités générales", example: "Water boils at 100 degrees.", translation: "L'eau bout à 100 degrés." },
      { text: "Goûts, états, opinions (verbes d'état)", example: "She likes jazz and knows a lot about music.", translation: "Elle aime le jazz et s'y connaît en musique." },
      { text: "Horaires fixes", example: "The train leaves at 9:15.", translation: "Le train part à 9 h 15." },
    ],
    structure: {
      affirmative: "Sujet + verbe (base)  — he/she/it + verbe + s",
      negative: "Sujet + do not (don't) / does not (doesn't) + verbe (base)",
      question: "Do / Does + sujet + verbe (base) ?",
      shortAnswers: "Yes, I do. / No, she doesn't.",
    },
    auxiliary: "do / does (seulement pour la négation et les questions)",
    forms: [
      { label: "I / you / we / they", en: "work" },
      { label: "he / she / it", en: "works" },
      { label: "Négation (3ᵉ pers.)", en: "He doesn't work" },
      { label: "Question (3ᵉ pers.)", en: "Does he work?" },
    ],
    examples: [
      { en: "I drink coffee in the morning.", fr: "Je bois du café le matin." },
      { en: "My sister works in a hospital.", fr: "Ma sœur travaille dans un hôpital." },
      { en: "They don't live in Paris.", fr: "Ils n'habitent pas à Paris." },
      { en: "Does he speak English?", fr: "Est-ce qu'il parle anglais ?" },
      { en: "What time do you start work?", fr: "À quelle heure commences-tu à travailler ?" },
    ],
    commonErrors: [
      { wrong: "She work in a bank.", right: "She works in a bank.", why: "À la 3ᵉ personne du singulier (he/she/it), on ajoute -s au verbe." },
      { wrong: "Does she works here?", right: "Does she work here?", why: "Après do/does, le verbe reste à la forme de base : le -s est déjà porté par « does »." },
      { wrong: "He don't like fish.", right: "He doesn't like fish.", why: "Avec he/she/it, l'auxiliaire est does (doesn't)." },
      { wrong: "I am agree.", right: "I agree.", why: "« Agree » est un verbe en anglais : on n'utilise pas « be » (contrairement à « je suis d'accord »)." },
    ],
    signalWords: ["always", "usually", "often", "sometimes", "never", "every day", "on Mondays"],
    tips: [
      "Les adverbes de fréquence se placent AVANT le verbe : « I always eat breakfast » (mais après « be » : « She is always late »).",
      "-s devient -es après -s, -sh, -ch, -x, -o : watches, goes, washes.",
      "Consonne + y → -ies : study → studies. Voyelle + y → -ys : play → plays.",
    ],
    exercises: [
      { id: "ps1", type: "choose", prompt: "She ___ to school by bus.", options: ["go", "goes", "going", "is go"], answer: "goes", explain: "3ᵉ personne : go → goes." },
      { id: "ps2", type: "choose", prompt: "___ you like pizza?", options: ["Do", "Does", "Are", "Have"], answer: "Do" },
      { id: "ps3", type: "complete", prompt: "My brother ___ (play) football every Saturday.", answers: ["plays"], explain: "Voyelle + y → on ajoute simplement -s." },
      { id: "ps4", type: "complete", prompt: "They ___ (not / eat) meat.", answers: ["don't eat", "do not eat"], explain: "Négation : do not (don't) + verbe de base." },
      { id: "ps5", type: "translate", prompt: "Il travaille dans une banque.", answers: ["He works in a bank."] },
      { id: "ps6", type: "translate", prompt: "Est-ce que tu parles anglais ?", answers: ["Do you speak English?"] },
      { id: "ps7", type: "correct", prompt: "She don't like coffee.", answers: ["She doesn't like coffee.", "She does not like coffee."], explain: "Avec she, on utilise doesn't." },
      { id: "ps8", type: "correct", prompt: "Does he plays the guitar?", answers: ["Does he play the guitar?"], explain: "Après does, le verbe est à la forme de base." },
      { id: "ps9", type: "choose", prompt: "He ___ late on Fridays.", options: ["always is", "is always", "always are", "does always"], answer: "is always", explain: "Avec be, l'adverbe de fréquence se place après le verbe." },
      { id: "ps10", type: "create", prompt: "Écrivez une phrase au présent simple sur votre routine du matin (utilisez un adverbe comme usually ou always).", pattern: "\\b(always|usually|often|sometimes|every)\\b", example: "I usually drink tea in the morning." },
      { id: "ps11", type: "listen", sentence: "She usually walks to work.", explain: "Écoutez et écrivez la phrase." },
    ],
  },
  {
    slug: "present-continuous",
    skillSlug: "present-continuous",
    title: "Present Continuous",
    titleFr: "Le présent continu",
    level: "A1",
    summary:
      "Le présent continu (be + verbe-ing) décrit ce qui se passe maintenant, autour de maintenant, ou un projet déjà organisé. Contrairement au français, l'anglais l'utilise systématiquement pour une action en cours.",
    whenToUse: [
      { text: "Action en train de se dérouler", example: "I'm talking to my teacher.", translation: "Je suis en train de parler à mon professeur." },
      { text: "Situation temporaire", example: "She's staying with her aunt this week.", translation: "Elle loge chez sa tante cette semaine." },
      { text: "Projet futur déjà organisé", example: "We're meeting Tom at 7 tonight.", translation: "Nous retrouvons Tom à 19 h ce soir." },
      { text: "Changement en cours", example: "Prices are rising.", translation: "Les prix augmentent." },
    ],
    structure: {
      affirmative: "Sujet + am / is / are + verbe-ing",
      negative: "Sujet + am / is / are + not + verbe-ing",
      question: "Am / Is / Are + sujet + verbe-ing ?",
      shortAnswers: "Yes, I am. / No, he isn't.",
    },
    auxiliary: "be (am / is / are)",
    forms: [
      { label: "I", en: "I'm working" },
      { label: "he / she / it", en: "She's working" },
      { label: "you / we / they", en: "They're working" },
      { label: "Question", en: "Are you working?" },
    ],
    examples: [
      { en: "It's raining.", fr: "Il pleut (en ce moment)." },
      { en: "I'm not watching TV.", fr: "Je ne regarde pas la télé." },
      { en: "What are you doing?", fr: "Qu'est-ce que tu fais ?" },
      { en: "They're having dinner.", fr: "Ils sont en train de dîner." },
      { en: "He's learning English this year.", fr: "Il apprend l'anglais cette année." },
    ],
    commonErrors: [
      { wrong: "I'm knowing the answer.", right: "I know the answer.", why: "Les verbes d'état (know, like, love, want, understand…) ne s'emploient normalement pas au continu." },
      { wrong: "She is work now.", right: "She is working now.", why: "Il faut ajouter -ing au verbe après be." },
      { wrong: "I am agree.", right: "I agree.", why: "« Agree » est un verbe : pas de « be »." },
      { wrong: "Are you coming from France?", right: "Do you come from France? / Where are you from?", why: "L'origine est un fait permanent : présent simple." },
    ],
    signalWords: ["now", "at the moment", "right now", "currently", "today", "this week", "look!", "listen!"],
    tips: [
      "Orthographe : make → making (on enlève le e), run → running (on double la consonne), lie → lying.",
      "Verbes d'état à éviter au continu : know, understand, believe, like, love, hate, want, need, prefer, belong.",
      "Pour un futur proche organisé (rendez-vous, billets pris), le présent continu est très naturel.",
    ],
    exercises: [
      { id: "pc1", type: "choose", prompt: "Look! It ___ .", options: ["snows", "is snowing", "snowing", "does snow"], answer: "is snowing" },
      { id: "pc2", type: "choose", prompt: "I ___ the answer.", options: ["am knowing", "know", "knowing", "does know"], answer: "know", explain: "Know est un verbe d'état : présent simple." },
      { id: "pc3", type: "complete", prompt: "They ___ (watch) a film right now.", answers: ["are watching", "'re watching"], explain: "are + watching" },
      { id: "pc4", type: "complete", prompt: "She ___ (not / work) today.", answers: ["isn't working", "is not working", "'s not working"] },
      { id: "pc5", type: "translate", prompt: "Je suis en train de cuisiner.", answers: ["I'm cooking.", "I am cooking."] },
      { id: "pc6", type: "translate", prompt: "Qu'est-ce que tu lis ?", answers: ["What are you reading?"] },
      { id: "pc7", type: "correct", prompt: "He is play football now.", answers: ["He is playing football now.", "He's playing football now."], explain: "be + verbe-ing." },
      { id: "pc8", type: "correct", prompt: "I am wanting a coffee.", answers: ["I want a coffee."], explain: "Want est un verbe d'état." },
      { id: "pc9", type: "choose", prompt: "Spelling: run → ___", options: ["runing", "running", "runming", "runeing"], answer: "running", explain: "On double la consonne finale (CVC)." },
      { id: "pc10", type: "create", prompt: "Écrivez une phrase qui décrit ce que vous faites en ce moment.", pattern: "\\b(am|is|are|'m|'re|'s)\\s+\\w+ing\\b", example: "I'm learning English on my phone." },
      { id: "pc11", type: "listen", sentence: "They are waiting for the bus.", explain: "Écoutez et écrivez la phrase." },
    ],
  },
  {
    slug: "past-simple",
    skillSlug: "past-simple",
    title: "Past Simple",
    titleFr: "Le prétérit simple",
    level: "A2",
    summary:
      "Le past simple raconte des actions terminées à un moment précis du passé (« yesterday », « last week », « in 2019 »). Il remplace à la fois le passé composé et le passé simple français à l'oral.",
    whenToUse: [
      { text: "Action terminée à un moment précis", example: "I went to the beach yesterday.", translation: "Je suis allé à la plage hier." },
      { text: "Succession d'actions (récit)", example: "She opened the door, looked outside and smiled.", translation: "Elle a ouvert la porte, a regardé dehors et a souri." },
      { text: "Habitude passée", example: "We played tennis every Sunday.", translation: "Nous jouions au tennis chaque dimanche." },
      { text: "Question sur le passé avec did", example: "Did you see the film?", translation: "As-tu vu le film ?" },
    ],
    structure: {
      affirmative: "Sujet + verbe au passé (regular : -ed ; irregular : forme spéciale)",
      negative: "Sujet + did not (didn't) + verbe (base)",
      question: "Did + sujet + verbe (base) ?",
      shortAnswers: "Yes, I did. / No, we didn't.",
    },
    auxiliary: "did (négation et questions) — be : was / were",
    forms: [
      { label: "Verbes réguliers", en: "work → worked" },
      { label: "Verbes irréguliers", en: "go → went, see → saw, buy → bought" },
      { label: "Négation", en: "I didn't go" },
      { label: "Question", en: "Did you go?" },
      { label: "be", en: "I/he/she/it was · you/we/they were" },
    ],
    examples: [
      { en: "I visited my grandparents last weekend.", fr: "J'ai rendu visite à mes grands-parents le week-end dernier." },
      { en: "She didn't come to the party.", fr: "Elle n'est pas venue à la fête." },
      { en: "Did you finish your homework?", fr: "As-tu fini tes devoirs ?" },
      { en: "We saw a great film on Friday.", fr: "Nous avons vu un super film vendredi." },
      { en: "Where did he go?", fr: "Où est-il allé ?" },
    ],
    commonErrors: [
      { wrong: "I go to the beach yesterday.", right: "I went to the beach yesterday.", why: "Avec « yesterday », « last… », « ago », on utilise obligatoirement le past simple." },
      { wrong: "Did you went there?", right: "Did you go there?", why: "Après did, le verbe revient à la forme de base : le passé est déjà dans « did »." },
      { wrong: "I didn't saw him.", right: "I didn't see him.", why: "Même règle : didn't + base verbale." },
      { wrong: "I have seen him yesterday.", right: "I saw him yesterday.", why: "Pas de present perfect avec une date précise." },
      { wrong: "She buyed a dress.", right: "She bought a dress.", why: "Buy est irrégulier : buy → bought." },
    ],
    signalWords: ["yesterday", "last week", "last year", "two days ago", "in 2019", "when I was young", "then"],
    tips: [
      "Verbes réguliers : -ed (worked), -d si finit par e (liked), consonne + y → -ied (studied), CVC → on double (stopped).",
      "Apprenez les 30 verbes irréguliers les plus fréquents en priorité : be, have, do, say, go, get, make, know, think, take, see, come…",
      "Dans une question ou une négation, le passé est porté par « did » uniquement.",
    ],
    exercises: [
      { id: "pas1", type: "choose", prompt: "I ___ to the cinema yesterday.", options: ["go", "went", "gone", "goed"], answer: "went" },
      { id: "pas2", type: "choose", prompt: "___ you see the match last night?", options: ["Do", "Did", "Have", "Were"], answer: "Did" },
      { id: "pas3", type: "complete", prompt: "She ___ (buy) a new phone last week.", answers: ["bought"] },
      { id: "pas4", type: "complete", prompt: "We ___ (not / go) out on Saturday.", answers: ["didn't go", "did not go"] },
      { id: "pas5", type: "translate", prompt: "Hier, j'ai mangé une pizza.", answers: ["Yesterday, I ate a pizza.", "Yesterday I ate a pizza.", "I ate a pizza yesterday."] },
      { id: "pas6", type: "translate", prompt: "Où es-tu allé en vacances ?", answers: ["Where did you go on holiday?", "Where did you go on vacation?"] },
      { id: "pas7", type: "correct", prompt: "I go to the beach yesterday.", answers: ["I went to the beach yesterday."], explain: "yesterday → past simple : go → went." },
      { id: "pas8", type: "correct", prompt: "Did she came to the party?", answers: ["Did she come to the party?"], explain: "Après did, verbe de base." },
      { id: "pas9", type: "correct", prompt: "He didn't saw the sign.", answers: ["He didn't see the sign.", "He did not see the sign."], explain: "didn't + base verbale." },
      { id: "pas10", type: "choose", prompt: "Past of \"study\":", options: ["studyed", "studied", "studdied", "studed"], answer: "studied" },
      { id: "pas11", type: "create", prompt: "Écrivez une phrase au passé sur ce que vous avez fait hier (utilisez « yesterday » ou « last night »).", pattern: "\\b(yesterday|last|ago)\\b", example: "Yesterday I met my friends in the park." },
      { id: "pas12", type: "listen", sentence: "We went to the beach last summer.", explain: "Écoutez et écrivez la phrase." },
    ],
  },
  {
    slug: "present-perfect",
    skillSlug: "present-perfect",
    title: "Present Perfect",
    titleFr: "Le présent parfait",
    level: "B1",
    summary:
      "Le present perfect (have/has + participe passé) relie le passé au présent : expérience de vie, résultat visible maintenant, ou situation qui continue (avec for/since). Attention : ce n'est PAS le passé composé français.",
    whenToUse: [
      { text: "Expérience de vie (sans date)", example: "I have visited Rome twice.", translation: "J'ai visité Rome deux fois." },
      { text: "Résultat présent d'une action récente", example: "I've lost my keys. (I can't get in.)", translation: "J'ai perdu mes clés (je ne peux pas entrer)." },
      { text: "Situation qui continue : for / since", example: "She has lived here for ten years.", translation: "Elle habite ici depuis dix ans." },
      { text: "Nouvelles récentes, just / already / yet", example: "They have just arrived.", translation: "Ils viennent d'arriver." },
    ],
    structure: {
      affirmative: "Sujet + have / has + participe passé",
      negative: "Sujet + have / has + not (haven't / hasn't) + participe passé",
      question: "Have / Has + sujet + participe passé ?",
      shortAnswers: "Yes, I have. / No, she hasn't.",
    },
    auxiliary: "have / has",
    forms: [
      { label: "Réguliers", en: "worked, played, studied" },
      { label: "Irréguliers", en: "been, gone, seen, done, eaten, written" },
      { label: "Affirmatif", en: "I've seen it · She's seen it" },
      { label: "Question", en: "Have you ever been to London?" },
    ],
    examples: [
      { en: "Have you ever eaten sushi?", fr: "As-tu déjà mangé des sushis ?" },
      { en: "I've known him since 2015.", fr: "Je le connais depuis 2015." },
      { en: "She hasn't called me yet.", fr: "Elle ne m'a pas encore appelé." },
      { en: "We've lived here for three years.", fr: "Nous habitons ici depuis trois ans." },
      { en: "He has already finished.", fr: "Il a déjà fini." },
    ],
    commonErrors: [
      { wrong: "I have seen him yesterday.", right: "I saw him yesterday.", why: "Une date précise (yesterday, last week, in 2019) exige le past simple." },
      { wrong: "I live here since 2020.", right: "I have lived here since 2020.", why: "Une situation qui dure jusqu'à maintenant : present perfect avec since/for, pas présent simple." },
      { wrong: "I am here for two hours.", right: "I have been here for two hours.", why: "Même logique : durée jusqu'à maintenant." },
      { wrong: "Since three years.", right: "For three years.", why: "for + durée ; since + point de départ (since 2020)." },
      { wrong: "I have went to Spain.", right: "I have been to Spain / I have gone to Spain.", why: "Participe passé de go : gone (been = y être allé et revenu)." },
    ],
    signalWords: ["ever", "never", "already", "yet", "just", "so far", "for", "since", "recently", "how long"],
    tips: [
      "for + durée (for two years) ; since + moment de départ (since Monday).",
      "have been to = être allé et en être revenu ; have gone to = être parti (et y être encore).",
      "Dès que vous pouvez dire QUAND, passez au past simple.",
    ],
    exercises: [
      { id: "pp1", type: "choose", prompt: "I ___ never ___ sushi.", options: ["have / eaten", "has / eaten", "have / ate", "did / eat"], answer: "have / eaten" },
      { id: "pp2", type: "choose", prompt: "She has lived here ___ 2018.", options: ["for", "since", "during", "from"], answer: "since" },
      { id: "pp3", type: "complete", prompt: "We ___ (live) in this city for five years.", answers: ["have lived", "'ve lived"] },
      { id: "pp4", type: "complete", prompt: "He ___ (not / finish) his homework yet.", answers: ["hasn't finished", "has not finished"] },
      { id: "pp5", type: "translate", prompt: "Je n'ai jamais été à Londres.", answers: ["I have never been to London.", "I've never been to London."] },
      { id: "pp6", type: "translate", prompt: "Elle travaille ici depuis deux ans.", answers: ["She has worked here for two years.", "She's worked here for two years.", "She has been working here for two years."] },
      { id: "pp7", type: "correct", prompt: "I live here since 2020.", answers: ["I have lived here since 2020.", "I've lived here since 2020.", "I have been living here since 2020."], explain: "Durée jusqu'à maintenant : present perfect." },
      { id: "pp8", type: "correct", prompt: "I have seen him yesterday.", answers: ["I saw him yesterday."], explain: "yesterday → past simple." },
      { id: "pp9", type: "choose", prompt: "Past participle of \"write\":", options: ["wrote", "written", "writed", "writen"], answer: "written" },
      { id: "pp10", type: "create", prompt: "Écrivez une phrase avec « have ever » ou « have never » sur une expérience de votre vie.", pattern: "\\b(have|'ve|has)\\s+(ever|never)\\b", example: "I have never been to Australia." },
      { id: "pp11", type: "listen", sentence: "I have lived here for three years.", explain: "Écoutez et écrivez la phrase." },
    ],
  },
  {
    slug: "future-forms",
    skillSlug: "future-forms",
    title: "Future forms",
    titleFr: "Les formes du futur",
    level: "A2",
    summary:
      "L'anglais n'a pas un seul futur mais trois formes courantes : will (décision spontanée, prédiction, promesse), be going to (intention, preuve présente) et le présent continu (rendez-vous déjà organisé).",
    whenToUse: [
      { text: "will — décision prise à l'instant, promesse, offre", example: "I'll help you with that bag.", translation: "Je vais t'aider avec ce sac." },
      { text: "will — prédiction, opinion sur le futur", example: "I think it will rain tomorrow.", translation: "Je pense qu'il pleuvra demain." },
      { text: "be going to — intention déjà décidée", example: "I'm going to learn Spanish next year.", translation: "Je vais apprendre l'espagnol l'an prochain." },
      { text: "be going to — prévision d'après un indice", example: "Look at those clouds! It's going to rain.", translation: "Regarde ces nuages ! Il va pleuvoir." },
      { text: "Présent continu — rendez-vous organisé", example: "I'm meeting Anna at six.", translation: "Je retrouve Anna à dix-huit heures." },
    ],
    structure: {
      affirmative: "will + base · am/is/are going to + base · am/is/are + verbe-ing",
      negative: "will not (won't) + base · am/is/are not going to + base",
      question: "Will + sujet + base ? · Are you going to + base ?",
      shortAnswers: "Yes, I will. / No, I won't.",
    },
    auxiliary: "will / be (going to)",
    forms: [
      { label: "will", en: "I will call you. · I'll call you." },
      { label: "going to", en: "She is going to travel." },
      { label: "Négation will", en: "They won't come." },
      { label: "Question going to", en: "Are you going to stay?" },
    ],
    examples: [
      { en: "I'll have the soup, please.", fr: "Je prendrai la soupe, s'il vous plaît." },
      { en: "We're going to buy a house.", fr: "Nous allons acheter une maison." },
      { en: "What are you doing tonight?", fr: "Que fais-tu ce soir ?" },
      { en: "It won't be easy.", fr: "Ce ne sera pas facile." },
      { en: "Will you marry me?", fr: "Veux-tu m'épouser ?" },
    ],
    commonErrors: [
      { wrong: "If it will rain, I will stay home.", right: "If it rains, I will stay home.", why: "Après if / when / as soon as, on utilise le présent (pas will)." },
      { wrong: "I will to go.", right: "I will go.", why: "will est suivi du verbe de base sans « to »." },
      { wrong: "I go to the cinema tomorrow.", right: "I'm going to the cinema tomorrow.", why: "Pour un projet, utilisez going to ou le présent continu, pas le présent simple (sauf horaires)." },
      { wrong: "She will goes tomorrow.", right: "She will go tomorrow.", why: "Jamais de -s après will." },
    ],
    signalWords: ["tomorrow", "next week", "tonight", "soon", "in two days", "probably", "I think", "I'm sure"],
    tips: [
      "Décision à l'instant → will. Plan déjà fait → going to. Rendez-vous avec heure/lieu → présent continu.",
      "En conversation, will se contracte presque toujours : I'll, you'll, she'll.",
      "Après when, if, as soon as, before, until : présent, même pour parler du futur.",
    ],
    exercises: [
      { id: "ff1", type: "choose", prompt: "The phone is ringing. — I ___ get it!", options: ["will", "am going to", "am getting", "get"], answer: "will", explain: "Décision spontanée." },
      { id: "ff2", type: "choose", prompt: "Look at the sky! It ___ rain.", options: ["will", "is going to", "rains", "is raining"], answer: "is going to", explain: "Indice visible → going to." },
      { id: "ff3", type: "complete", prompt: "I ___ (not / be) late, I promise.", answers: ["won't be", "will not be"] },
      { id: "ff4", type: "complete", prompt: "We ___ (go) to the cinema tonight. We've got tickets.", answers: ["are going", "'re going", "are going to go", "'re going to go"] },
      { id: "ff5", type: "translate", prompt: "Je vais apprendre le piano.", answers: ["I'm going to learn the piano.", "I am going to learn the piano.", "I'm going to learn piano."] },
      { id: "ff6", type: "translate", prompt: "Il pleuvra demain, je pense.", answers: ["I think it will rain tomorrow.", "I think it'll rain tomorrow.", "It will rain tomorrow, I think."] },
      { id: "ff7", type: "correct", prompt: "If it will rain, we will stay home.", answers: ["If it rains, we will stay home.", "If it rains, we'll stay home."], explain: "Après if : présent simple." },
      { id: "ff8", type: "correct", prompt: "She will goes to Paris next week.", answers: ["She will go to Paris next week.", "She'll go to Paris next week."], explain: "will + base." },
      { id: "ff9", type: "choose", prompt: "I'll call you when I ___ home.", options: ["will get", "get", "am getting", "got"], answer: "get" },
      { id: "ff10", type: "create", prompt: "Écrivez une phrase avec « going to » sur vos projets pour le week-end.", pattern: "\\bgoing to\\b", example: "I'm going to visit my parents this weekend." },
      { id: "ff11", type: "listen", sentence: "I will call you tomorrow morning.", explain: "Écoutez et écrivez la phrase." },
    ],
  },
];

export const lessonBySlug = (slug: string) => GRAMMAR_LESSONS.find((l) => l.slug === slug);
